utils::globalVariables(
  c(
    ".",
    "bacia_hidrografica",
    "contains",
    "link_representantes",
    "links",
    "n_ugrhi",
    "name",
    "nome",
    "nome_1",
    "ordem",
    "posicao_blocos",
    "set",
    "sigla_comite",
    "value",
    "data_documento",
    "desc_data",
    "id_bloco",
    "id_lista",
    "link_numero",
    "eh_h2",
    "h2",
    "conteudo"
  )
)
